[package]
name = "ezra"
version = "1.0.0"
edition = "2021"
description = "Ezra — a readable scripting language built in Rust"
authors = ["Ankur Rana"]
license = "MIT"
repository = "https://github.com/ranaji114/Flux-programming-lang"
homepage = "https://ranaji114.github.io/Flux-programming-lang"
keywords = ["language", "interpreter", "scripting", "ezra"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "ezra"
path = "src/main.rs"

[[bin]]
name = "ezra-lsp"
path = "src/lsp_server.rs"

[profile.release]
strip = true
opt-level = 3
lto = true

[dependencies]
serde_json = "1"
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
